
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn package -DskipTests

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/rafaresearch/jenkins/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-fdae5a359f9be971f93d127baa770b9b395c2f15
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            